#! /bin/sh

DIE=0

rm -f mkinstalldirs missing depcomp install-sh 

(autoconf --version) < /dev/null > /dev/null 2>&1 || {
    echo
        echo "You must have autoconf installed."
	DIE=1
}

# libtool --version check not done...

(automake --version) < /dev/null > /dev/null 2>&1 || {
    echo
        echo "You must have automake installed."
        DIE=1
}

if test "$DIE" -eq 1; then
    exit 1
fi

echo "aclocal -I ."
aclocal -I . 
if test $? -ne 0; then
    exit 1
fi
echo "autoheader"
autoheader
if test $? -ne 0; then
    exit 1
fi

rm -f config.sub config.guess
echo "automake --foreign --add-missing"
automake --foreign --add-missing
if test $? -ne 0; then
    exit 1
fi
echo "autoconf"
autoconf
echo "BOOTSTRAP complete"

